### ISSUE TITLE
Web App to Encode/Decode hex strings

### ISSUE THREAD

**Issue by Chasmiccoder** [ACM-VIT/Algos-for-all-Amigos#6]
Hey there! Welcome to Hacktoberfest 2021!
---
Thanks for taking interest in this project.

We want to develop a website that can be used to solve Cybersecurity Related Tasks.
One really useful feature will be a script to convert strings from Hexadecimal to ascii
The website needs to be fully responsive!

Tech Stack - HTML, CSS, JS

Example -
| Type | String |
|-|-|
| ASCII | "Hello World" |
| Hex | "48 65 6c 6c 6f 20 57 6f 72 6c 64" |

---
It's okay if you don't finish 100% of what is required, it's the attempt that matters!
We'll accept PRs even if they complete a sub-component of this issue 
(depending on the code submitted and the effort taken) 
All the best :D

**Comment by Karun842002** [comment]
Can I be assigned this issue please?

**Comment by Chasmiccoder** [comment]
Hi @Karun842002 !
I've assigned the Vigenere Cipher one already.
I can't assign you to more than 1 issue, but incase this issue remains open (and no one comments),
you can make a PR and we'll merge it!

Thanks for taking interest!

**Comment by Anshika0924** [comment]
Hey! Can you assign this issue to me?

**Comment by Chasmiccoder** [comment]
Hi @Anshika0924 !
Sure.
Assigning this to you

**Comment by Anshika0924** [comment]
Yes, almost done..will make a pr today!

**Comment by Chasmiccoder** [comment]
@Anshika0924 
That sounds great :D

**Comment by Anshika0924** [comment]
what should be the name of the folder?
