### ISSUE TITLE
Web App to Encode/Decode Caesar Cipher

### ISSUE THREAD

**Issue by Chasmiccoder** [ACM-VIT/Algos-for-all-Amigos#7]
Hey there! Welcome to Hacktoberfest 2021!
---
Thanks for taking interest in this project.

We want to develop a website that can be used to solve Cybersecurity Related Tasks.
One really useful feature will be a script to encrypt and decrypt strings with the Caesar's Cipher
The website needs to be fully responsive!

Tech Stack - HTML, CSS, JS

Example - (Key = 3)
| Type | String |
|-|-|
| Plaintext | "Hello World" |
| Ciphertext | "Khoor Zruog" |

---
It's okay if you don't finish 100% of what is required, it's the attempt that matters!
We'll accept PRs even if they complete a sub-component of this issue 
(depending on the code submitted and the effort taken) 
All the best :D

**Comment by Prasang023** [comment]
Hey! Can i work on this...being a beginner, might need some guidance.

**Comment by Karun842002** [comment]
Can I be assigned this issue please?

**Comment by Chasmiccoder** [comment]
@Prasang023 
Hi there! Sure
I'll assign you

**Comment by Chasmiccoder** [comment]
Hi @Karun842002 
Really sorry about that, but Prasang asked before.
You can try for another issue. They're pretty easy and I'll assign one to you as soon as you comment

Thanks for taking interest.

**Comment by Prasang023** [comment]
@Chasmiccoder, in which folder should I add this project in current repository structure ?

**Comment by Chasmiccoder** [comment]
@Prasang023 

There's a new folder under Computer_Science titled as Cryptography. Within that Cryptography folder, there is one on RSA. So we need you to create a new folder beside RSA (under Cryptography) and call it Caesar_Cipher.
Place all your files in this newly created folder Caesar_Cipher

Thanks!

**Comment by Chasmiccoder** [comment]
@Prasang023 
Thank you for contributing!
