### ISSUE TITLE
Web App to Encrypt/Decrypt Vigenere Cipher

### ISSUE THREAD

**Issue by Chasmiccoder** [ACM-VIT/Algos-for-all-Amigos#8]
Hey there! Welcome to Hacktoberfest 2021!
---
Thanks for taking interest in this project.

We want to develop a website that can be used to solve Cybersecurity Related Tasks.
One really useful feature will be a script to encrypt and decrypt the Vigenere Cipher
The website needs to be fully responsive!

Tech Stack - HTML, CSS, JS

Example - (Key = ACM)
| Type | String |
|-|-|
| Plaintext | "Hello World" |
| Ciphertext | "Hgxlq iotxd" |

---
It's okay if you don't finish 100% of what is required, it's the attempt that matters!
We'll accept PRs even if they complete a sub-component of this issue 
(depending on the code submitted and the effort taken) 
All the best :D

**Comment by Karun842002** [comment]
Could you please assign me this issue?

**Comment by Chasmiccoder** [comment]
Hi @Karun842002 !
Yes, sure
You've been assigned to solve this issue
Thanks

**Comment by Chasmiccoder** [comment]
Hi @Karun842002 !
Is there any update on this issue?

**Comment by Chasmiccoder** [comment]
@Karun842002 
Okay sure
